INSERT INTO DEPARTMENTS (ID, FULL_NAME, SHORT_CUT, CREATION_DATE) VALUES ( 1, 'Research and Development', 'R&D', '2020-01-15');
INSERT INTO DEPARTMENTS (ID, FULL_NAME, SHORT_CUT, CREATION_DATE) VALUES ( 2, 'Preparation', 'PRP', '2020-01-15');
INSERT INTO DEPARTMENTS (ID, FULL_NAME, SHORT_CUT, CREATION_DATE) VALUES ( 3, 'Assembling', 'ASM', '2020-01-15');
INSERT INTO DEPARTMENTS (ID, FULL_NAME, SHORT_CUT, CREATION_DATE) VALUES ( 4, 'Finishing', 'FSH', '2020-01-15');